from PyQt5 import QtCore, QtWidgets
from forms.py.lagging_students import FormLaggingStudents


class FormDiagram(object):
    def __init__(self, main_window):
        self.diagram_window = main_window.diagram_window
        self.diagram_window.setObjectName("MainWindow")
        self.diagram_window.resize(800, 563)
        self.centralwidget = QtWidgets.QWidget(self.diagram_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 781, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 592, 419))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.place_to_show_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.place_to_show_graph.setGeometry(QtCore.QRect(12, 12, 498, 335))
        self.place_to_show_graph.setText("")
        self.place_to_show_graph.setObjectName("place_to_show_graph")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 4, 0, 13, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.show_lagging_students_window)
        self.gridLayout.addWidget(self.pushButton_2, 9, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 500, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.close_window)
        self.diagram_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self.diagram_window)
        self.statusbar.setObjectName("statusbar")
        self.diagram_window.setStatusBar(self.statusbar)

        self.lagging_students_window = QtWidgets.QMainWindow()
        self.lagging_students_ui = FormLaggingStudents(self)

        self.retranslateUi(self.diagram_window)
        QtCore.QMetaObject.connectSlotsByName(self.diagram_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аналитика: вывод диаграммы"))
        self.label.setText(_translate("MainWindow", "Диаграмма"))
        self.label_2.setText(_translate("MainWindow", "Параметры"))
        self.label_3.setText(_translate("MainWindow", "Дисциплина:"))
        self.label_4.setText(_translate("MainWindow", "Наименование"))
        self.pushButton_2.setText(_translate("MainWindow", "Отстающие студенты"))
        self.label_5.setText(_translate("MainWindow", "Группа:"))
        self.label_6.setText(_translate("MainWindow", "Наименование группы"))
        self.pushButton.setText(_translate("MainWindow", "Закрыть"))

    def show_lagging_students_window(self):
        self.lagging_students_window.show()
        self.diagram_window.hide()

    def close_window(self):
        self.diagram_window.close()